version: "2"
services:
  app:
    image:  golang:1.9.2-alpine3.6
    volumes:
      - .:/go/src/github.com/riquellopes/tracker-api
    working_dir: /go/src/github.com/riquellopes/tracker-api
    command: go run main.go
    links:
      - mongodb
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - DATABASE=tracker
      - SERVER=mongodb
  mongodb:
    image: mvertes/alpine-mongo
